wmp/bom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (BomDetailView,
					BomListView,
					BomDetailListView,
					BomDetailDetailView)


urlpatterns = [
	# Page
	url(r'^$',BomListView.as_view(),name='list'),
	url(r'^item/$',BomDetailListView.as_view(),name='item-list'),
	url(r'^item/(?P<slug>[-\w]+)/$',BomDetailDetailView.as_view(),name='item-detail'),
    url(r'^(?P<slug>[-\w]+)/$',BomDetailView.as_view(),name='detail'),

]

wmp/snippet/api/urls.py
# from django.conf.urls import url
# from django.contrib import admin
# from rest_framework.urlpatterns import format_suffix_patterns

# from .views import (
#     # SnippetListAPIView,
#     # SnippetDetailAPIView,
#     # SnippetCreateAPIView,
#     # SnippetDeleteAPIView,
#     # SnippetUpdateAPIView,
#     SnippetList,
#     SnippetDetail
#     )

# urlpatterns = [
# 	url(r'^$', SnippetList.as_view(), name='list'),
# 	# url(r'^create/$',SnippetCreateAPIView.as_view(),name='create'),
# 	url(r'^(?P<slug>[\w-]+)/$',SnippetDetail.as_view(), name='detail'),
# 	# url(r'^(?P<slug>[\w-]+)/delete/$', SnippetDeleteAPIView.as_view(),name='delete'),
# 	# url(r'^(?P<slug>[\w-]+)/update/$', SnippetUpdateAPIView.as_view(),name='update'),
 
# ]


# urlpatterns = format_suffix_patterns(urlpatterns)

wmp/snippet/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (SnippetDetailView,
					SnippetListView,
					SnippetHighlight)


urlpatterns = [
	# Page
	url(r'^$',SnippetListView.as_view(),name='list'),
    url(r'^(?P<slug>[-\w]+)/$',SnippetDetailView.as_view(),name='detail'),
    url(r'^(?P<slug>[-\w]+)/highlight/$', SnippetHighlight.as_view(),name='highlight'),
]

wmp/wmp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .routers import router

from . import views

from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    url(r'^$',views.home ,name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^graphql/', GraphQLView.as_view(
        graphiql =True,
        schema=schema
    )),
    # Token
    url(r'^api/', include(router.urls)),
    url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),

    
    url(r'^assembly/',include(('assembly.urls','assembly'),namespace='assembly')),
    url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
    url(r'^component/',include(('component.urls','component'),namespace='component')),
    url(r'^cache/',include(('cache.urls','cache'),namespace='cache')),
    url(r'^item/',include(('item.urls','item'),namespace='item')),
    url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
    url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
    url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
    url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
    url(r'^product/',include(('product.urls','product'),namespace='product')),
    url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
    url(r'^routing-detail/',include(('routing.urls','routing-detail'),namespace='routing-detail')),
    url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
    url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
    url(r'^symptom/',include(('symptom.urls','symptom'),namespace='symptom')),
    url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib import admin
# admin.site.site_header = '8 O\'Clock Manufacturing Platform'
# admin.site.site_title = '8 O\'Clock Manufacturing Platform'

admin.site.site_header = '8AM Manufacturing Platform'
admin.site.site_title = '8AM Manufacturing Platform'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'wmp.views.bad_request'
# handler403 = 'wmp.views.permission_denied'
# handler404 = 'wmp.views.page_not_found'
# handler500 = 'wmp.views.server_error'

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # Page
    
#     url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
#     url(r'^bom-detail/',include(('bom_detail.urls','bom_detail'),namespace='bom_detail')),
#     url(r'^hook/',include(('hook.urls','hook'),namespace='hook')),
#     url(r'^item/',include(('item.urls','item'),namespace='item')),
#     url(r'^item-list/',include(('item_list.urls','item_list'),namespace='item-list')),
#     url(r'^failure/',include(('failure.urls','failure'),namespace='failure')),
#     url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
#     url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
#     url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
#     url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
#     url(r'^product/',include(('product.urls','product'),namespace='product')),
#     url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
#     url(r'^routing-accept/',include(('routing_accept.urls','routing_accept'),namespace='routing-accept')),
#     url(r'^routing-detail/',include(('routing_detail.urls','routing_detail'),namespace='routing-detail')),
#     url(r'^routing-next/',include(('routing_next.urls','routing_next'),namespace='routing-next')),
#     url(r'^routing-reject/',include(('routing_reject.urls','routing_reject'),namespace='routing-reject')),
#     url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
#     url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
#     url(r'^symptom-code/',include(('symptom_code.urls','symptom_code'),namespace='symptom-code')),
#     url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    
#     # API
#     url(r'api/bom/', include(('bom.api.urls','bom'), namespace='bom-api')),
#     url(r'api/bom-detail/', include(("bom_detail.api.urls",'bom_detail'), namespace='bom_detail-api')),
#     url(r'api/defectcode/', include(("defect_code.api.urls",'defectcode'), namespace='defectcode-api')),
#     url(r'api/item/', include(("item.api.urls",'item'), namespace='item-api')),
#     url(r'api/item-list/', include(("item_list.api.urls",'item_list'), namespace='item_list-api')),
#     url(r'api/failure/', include(("failure.api.urls",'failure'), namespace='failure-api')),
#     url(r'api/hook/', include(("hook.api.urls",'hook'), namespace='hook-api')),
#     url(r'api/routing/', include(("routing.api.urls",'routing'), namespace='routing-api')),
#     url(r'api/routing-accept/', include(("routing_accept.api.urls",'routing_accept'), namespace='routing_accept-api')),
#     url(r'api/routing-next/', include(("routing_next.api.urls",'routing_next'), namespace='routing_next-api')),
#     url(r'api/routing-reject/', include(("routing_reject.api.urls",'routing_reject'), namespace='routing_reject-api')),
#     url(r'api/performing/', include(("performing.api.urls",'performing'), namespace='performing-api')),
#     url(r'api/serialnumber/', include(("serialnumber.api.urls",'serialnumber'), namespace='serialnumber-api')),
#     url(r'api/workorder/', include(("workorder.api.urls",'workorder'), namespace='workorder-api')),
#     url(r'api/product/', include(("product.api.urls",'product'), namespace='product-api')),
#     url(r'api/operation/', include(("operation.api.urls",'operation'), namespace='operation-api')), 
#     url(r'api/routing-detail/', include(("routing_detail.api.urls",'routing_detail'), namespace='routing_detail-api')),
#     url(r'api/parameter/', include(("parameter.api.urls",'parameter'), namespace='parameter-api')),
#     url(r'api/parametric/', include(("parametric.api.urls",'parametric'), namespace='parametric-api')),
#     url(r'api/snippet/', include(("snippet.api.urls",'snippet'), namespace='snippet-api')),
#     url(r'api/symptomcode/', include(("symptom_code.api.urls",'snippet'), namespace='symptomcode-api')),
#     url(r'api/user-profile/', include(("user_profile.api.urls",'user_profile'), namespace='userprofile-api')),

#     #Restful Authentication
#     url(r'^api-auth/', include('rest_framework.urls')),
#     # Token
#     url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
#     url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
#     url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
#     # url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
#     url(r'^report/wip/$',views.wip ,name='wip'),
#     url(r'^',views.home ,name='home'),

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wmp/snippet/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.conf import settings

from pygments.lexers import get_all_lexers
from pygments.styles import get_all_styles

from pygments.lexers import get_lexer_by_name
from pygments.formatters.html import HtmlFormatter
from pygments import highlight
from django.core.validators import RegexValidator


LEXERS = [item for item in get_all_lexers() if item[1]]
LANGUAGE_CHOICES = sorted([(item[1][0], item[0]) for item in LEXERS])
STYLE_CHOICES = sorted((item, item) for item in get_all_styles())

ACTIVE='A'
DEACTIVE='D'
STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DEACTIVE, 'Deactive'),
    )

class Snippet(models.Model):
	name 				= models.CharField(max_length=100,
							validators=[
									RegexValidator(
										regex='^[\w-]+$',
										message='Name does not allow special charecters',
									),
								])
	title 				= models.CharField(max_length=100,blank=True, null=True)
	description 		= models.TextField(max_length=255,blank=True, null=True)
	slug 				= models.SlugField(unique=True,blank=True, null=True)
	code 				= models.TextField()
	linenos 			= models.BooleanField(default=True)
	language 			= models.CharField(choices=LANGUAGE_CHOICES, default='vb.net', max_length=100)
	style 				= models.CharField(choices=STYLE_CHOICES, default='friendly', max_length=100)
	highlighted 		= models.TextField(blank=True, null=True)
	category1 			= models.CharField(max_length=50,blank=True, null=True)
	category2 			= models.CharField(max_length=50,blank=True, null=True)
	status 				= models.CharField(max_length=1,choices=STATUS_CHOICES,default=ACTIVE)
	created_date 		= models.DateTimeField(auto_now_add=True)
	modified_date 		= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 				= models.ForeignKey(settings.AUTH_USER_MODEL,
								on_delete=models.SET_NULL,
								related_name='snippets',blank=True,null=True)

	class Meta:
		ordering = ('created_date',)

	def __str__(self):
		return ('%s' % (self.name))

	def get_absolute_url(self):
		return reverse('snippet:detail', kwargs={'slug': self.slug})

	def save(self, *args, **kwargs):
	    """
	    Use the `pygments` library to create a highlighted HTML
	    representation of the code snippet.
	    """
	    lexer = get_lexer_by_name(self.language)
	    linenos = 'table' if self.linenos else False
	    # options = {'title': self.title} if self.title else {}
	    options = {'title': 'Code','nobackground':'true'} 
	    formatter = HtmlFormatter(style=self.style, linenos=linenos,
	                              full=True, **options)
	    self.highlighted = highlight(self.code, lexer, formatter)
	    super(Snippet, self).save(*args, **kwargs)


def create_snippet_slug(instance, new_slug=None):
    # import datetime
    default_slug = '%s' % (instance.name)
    slug = slugify(default_slug)
    if new_slug is not None:
        slug = new_slug
    qs = Snippet.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.count())
        return create_snippet_slug(instance, new_slug=new_slug)
    return slug

def pre_save_snippet_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_snippet_slug(instance)

pre_save.connect(pre_save_snippet_receiver, sender=Snippet)

wmp/snippet/api/views.py
# from django.db.models import Q

# from rest_framework import generics

# from rest_framework.generics import (
# 	CreateAPIView,
# 	DestroyAPIView,
# 	ListAPIView,
# 	UpdateAPIView,
# 	RetrieveAPIView,
# 	RetrieveUpdateAPIView,
# 	RetrieveUpdateDestroyAPIView
# 	)

# from rest_framework.filters import (
# 	SearchFilter,
# 	OrderingFilter,
# 	)

# from rest_framework.permissions import (
# 	AllowAny,
# 	IsAuthenticated,
# 	IsAdminUser,
# 	IsAuthenticatedOrReadOnly,
# 	)

# from rest_framework import permissions


# from snippet.models import Snippet
# from .serialize import (SnippetListSerializer,
# 						SnippetCreateSerializer,
# 						SnippetDetailSerializer,
# 						SnippetUpdateSerializer)

# from .permissions import IsOwnerOrReadOnly



# class SnippetList(generics.ListCreateAPIView):
# 	queryset 			= Snippet.objects.none()
# 	serializer_class 	= SnippetListSerializer
# 	filter_backends 	= [SearchFilter,OrderingFilter]
# 	search_fields 		= ['name']
# 	# permission_classes 	= (IsAuthenticatedOrReadOnly,
# 	# 					IsOwnerOrReadOnly)

# 	def perform_create(self, serializer):
# 		serializer.save(user=self.request.user),

# 	def get_queryset(self,*args,**kwargs):
# 		queryset_list = Snippet.objects.all()
# 		name = self.request.GET.get("name")
# 		if name != None :
# 			queryset_list = Snippet.objects.filter(
# 					Q(name__icontains = name))
# 		return queryset_list
# 	# pagination_class = PostPageNumberPagination

# class SnippetDetail(generics.RetrieveUpdateDestroyAPIView):
#     queryset 			= Snippet.objects.all()
#     lookup_field 		= 'slug'
#     serializer_class 	= SnippetDetailSerializer
#     # permission_classes 	= (IsAuthenticatedOrReadOnly,
#     # 					IsOwnerOrReadOnly,)


# # class SnippetDetailAPIView(RetrieveAPIView):
# # 	queryset= Snippet.objects.all()
# # 	serializer_class = SnippetDetailSerializer
# # 	lookup_field = 'slug'
# # 	# print ("vessel details")

# # class SnippetDeleteAPIView(DestroyAPIView):
# # 	queryset= Snippet.objects.all()
# # 	serializer_class= SnippetDetailSerializer
# # 	lookup_field='slug'
# # 	# permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]


# # class SnippetCreateAPIView(CreateAPIView):
# # 	queryset= Snippet.objects.all()
# # 	serializer_class= SnippetCreateSerializer
# # 	# permission_classes = [IsAuthenticated]

# # class SnippetUpdateAPIView(RetrieveUpdateDestroyAPIView):
# # 	queryset=Snippet.objects.all()
# # 	serializer_class=SnippetUpdateSerializer
# # 	lookup_field='slug'

wmp/snippet/views.py
from django.shortcuts import render

from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView

from rest_framework import generics
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.reverse import reverse
from rest_framework import renderers
from django.db.models import Q,F


from .models import Snippet



@api_view(['GET'])
def api_root(request, format=None):
	return Response({
		'users': reverse('user-api:list', request=request, format=format),
		'snippets': reverse('snippet-api:list', request=request, format=format)
	})


class SnippetListView(ListView):
	model = Snippet
	paginate_by = 100
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query :
			return Snippet.objects.filter(Q(name__icontains=query) |
									Q(title__icontains=query) |
									Q(description__icontains=query) ).order_by('-modified_date')
		return Snippet.objects.all().order_by('-modified_date')

class SnippetDetailView(DetailView):
	model = Snippet


class SnippetHighlight(generics.GenericAPIView):
	queryset = Snippet.objects.all()
	renderer_classes = (renderers.StaticHTMLRenderer,)
	lookup_field ='slug'

	def get(self, request, *args, **kwargs):
		snippet = self.get_object()
		return Response(snippet.highlighted)

wmp/templates/snippet/snippet_detail.html
{% extends "base.html" %}


{% block title %}
	Snippet : {{ object.name }}
{% endblock %}

{% block content %}
<div class="wrapper">

		<h1>Snippet : {{ object.name }}</h1>


	<a href="../">Back to Snippet list</a><br>
		<i>Created date : {{object.created_date}} -- {{object.created_user}}</i><br>
		<i>Modified date : {{object.modified_date}}</i>
    <div class="row">
          <div class="col-md-5">
            <h2>Basic Information</h2>
            <table class="table">
			  
			  <tbody>
			  	
			    <tr>
			      <td>Title</td>
			      <td>{{object.title}}</td>
			    </tr>

			    <tr>
			      <td>Description</td>
			      <td>{{object.description}}</td>
			    </tr>
			    <tr>
			      <td>Category1</td>
			      <td>{{object.category1}}</td>
			    </tr>
			    <tr>
			      <td>Category2</td>
			      <td>{{object.category2}}</td>
			    </tr>
		   
			    
			  </tbody>
			</table>
          </div>
           <div class="col-md-7">
           		 {{object.highlighted|safe}}
           </div>
    </div> 

   


</div>

{% endblock content %}

wmp/templates/snippet/snippet_list.html
{% extends 'base.html' %}

{% block title %}8AM - Snippet list{% endblock %}

{% block content %}

	<h1>Snippet List</h1>
  <a href="../"><i class="fa fa-home" style="font-size:24px;color:blue" aria-hidden="true"></i></a>
	<div class="wrapper">	


    <form class='form' method='GET' action='.'>
                        <input type='text' id='search' placeholder="Search Snippet" name="q" value='{{ request.GET.q}}'>
                        <button class='btn btn-default' type='submit'>Search</button>
                        <a href="{% url 'snippet:list'  %}">Clear result</a>
    </form>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Product name</th>
          <th scope="col">Title</th>
         <th scope="col">Created Date</th>
         <th scope="col">Modify Date</th>
         <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
		
    		{% for object in object_list %}
          <tr>
            <td><a href="{{object.get_absolute_url}}">{{object.name}}</a> </td>
            <td>{{object.title}} </td>
            <td>{{object.created_date}}</td>
            <td>{{object.modified_date}}</td>
            <td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
          </tr>
    		{% endfor %}
      </tbody>
    </table>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

	</div>
		
{% endblock content %}


{% block stylesheet %}
{% endblock stylesheet %}