wmp/assembly/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (AssemblyDetailView,
					AssemblyListView,
					AssemblyDetailDetailView)


urlpatterns = [
	# Page
	# url(r'^item/(?P<slug>[-\w]+)/$',AssemblyDetailView.as_view(),name='assembly-detail'),
	url(r'^$',AssemblyListView.as_view(),name='list'),
	url(r'^item/(?P<slug>[-\w]+)/$',AssemblyDetailDetailView.as_view(),name='assembly-detail'),
    url(r'^(?P<slug>[-\w]+)/$',AssemblyDetailView.as_view(),name='detail'),

]

wmp/bom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (BomDetailView,
					BomListView,
					BomDetailListView,
					BomDetailDetailView)


urlpatterns = [
	# Page
	url(r'^$',BomListView.as_view(),name='list'),
	url(r'^item/$',BomDetailListView.as_view(),name='item-list'),
	url(r'^item/(?P<slug>[-\w]+)/$',BomDetailDetailView.as_view(),name='item-detail'),
    url(r'^(?P<slug>[-\w]+)/$',BomDetailView.as_view(),name='detail'),

]

wmp/wmp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .routers import router

from . import views

from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    url(r'^$',views.home ,name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^graphql/', GraphQLView.as_view(
        graphiql =True,
        schema=schema
    )),
    # Token
    url(r'^api/', include(router.urls)),
    url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),

    
    url(r'^assembly/',include(('assembly.urls','assembly'),namespace='assembly')),
    url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
    url(r'^component/',include(('component.urls','component'),namespace='component')),
    url(r'^cache/',include(('cache.urls','cache'),namespace='cache')),
    url(r'^item/',include(('item.urls','item'),namespace='item')),
    url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
    url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
    url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
    url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
    url(r'^product/',include(('product.urls','product'),namespace='product')),
    url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
    url(r'^routing-detail/',include(('routing.urls','routing-detail'),namespace='routing-detail')),
    url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
    url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
    url(r'^symptom/',include(('symptom.urls','symptom'),namespace='symptom')),
    url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib import admin
# admin.site.site_header = '8 O\'Clock Manufacturing Platform'
# admin.site.site_title = '8 O\'Clock Manufacturing Platform'

admin.site.site_header = '8AM Manufacturing Platform'
admin.site.site_title = '8AM Manufacturing Platform'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'wmp.views.bad_request'
# handler403 = 'wmp.views.permission_denied'
# handler404 = 'wmp.views.page_not_found'
# handler500 = 'wmp.views.server_error'

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # Page
    
#     url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
#     url(r'^bom-detail/',include(('bom_detail.urls','bom_detail'),namespace='bom_detail')),
#     url(r'^hook/',include(('hook.urls','hook'),namespace='hook')),
#     url(r'^item/',include(('item.urls','item'),namespace='item')),
#     url(r'^item-list/',include(('item_list.urls','item_list'),namespace='item-list')),
#     url(r'^failure/',include(('failure.urls','failure'),namespace='failure')),
#     url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
#     url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
#     url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
#     url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
#     url(r'^product/',include(('product.urls','product'),namespace='product')),
#     url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
#     url(r'^routing-accept/',include(('routing_accept.urls','routing_accept'),namespace='routing-accept')),
#     url(r'^routing-detail/',include(('routing_detail.urls','routing_detail'),namespace='routing-detail')),
#     url(r'^routing-next/',include(('routing_next.urls','routing_next'),namespace='routing-next')),
#     url(r'^routing-reject/',include(('routing_reject.urls','routing_reject'),namespace='routing-reject')),
#     url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
#     url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
#     url(r'^symptom-code/',include(('symptom_code.urls','symptom_code'),namespace='symptom-code')),
#     url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    
#     # API
#     url(r'api/bom/', include(('bom.api.urls','bom'), namespace='bom-api')),
#     url(r'api/bom-detail/', include(("bom_detail.api.urls",'bom_detail'), namespace='bom_detail-api')),
#     url(r'api/defectcode/', include(("defect_code.api.urls",'defectcode'), namespace='defectcode-api')),
#     url(r'api/item/', include(("item.api.urls",'item'), namespace='item-api')),
#     url(r'api/item-list/', include(("item_list.api.urls",'item_list'), namespace='item_list-api')),
#     url(r'api/failure/', include(("failure.api.urls",'failure'), namespace='failure-api')),
#     url(r'api/hook/', include(("hook.api.urls",'hook'), namespace='hook-api')),
#     url(r'api/routing/', include(("routing.api.urls",'routing'), namespace='routing-api')),
#     url(r'api/routing-accept/', include(("routing_accept.api.urls",'routing_accept'), namespace='routing_accept-api')),
#     url(r'api/routing-next/', include(("routing_next.api.urls",'routing_next'), namespace='routing_next-api')),
#     url(r'api/routing-reject/', include(("routing_reject.api.urls",'routing_reject'), namespace='routing_reject-api')),
#     url(r'api/performing/', include(("performing.api.urls",'performing'), namespace='performing-api')),
#     url(r'api/serialnumber/', include(("serialnumber.api.urls",'serialnumber'), namespace='serialnumber-api')),
#     url(r'api/workorder/', include(("workorder.api.urls",'workorder'), namespace='workorder-api')),
#     url(r'api/product/', include(("product.api.urls",'product'), namespace='product-api')),
#     url(r'api/operation/', include(("operation.api.urls",'operation'), namespace='operation-api')), 
#     url(r'api/routing-detail/', include(("routing_detail.api.urls",'routing_detail'), namespace='routing_detail-api')),
#     url(r'api/parameter/', include(("parameter.api.urls",'parameter'), namespace='parameter-api')),
#     url(r'api/parametric/', include(("parametric.api.urls",'parametric'), namespace='parametric-api')),
#     url(r'api/snippet/', include(("snippet.api.urls",'snippet'), namespace='snippet-api')),
#     url(r'api/symptomcode/', include(("symptom_code.api.urls",'snippet'), namespace='symptomcode-api')),
#     url(r'api/user-profile/', include(("user_profile.api.urls",'user_profile'), namespace='userprofile-api')),

#     #Restful Authentication
#     url(r'^api-auth/', include('rest_framework.urls')),
#     # Token
#     url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
#     url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
#     url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
#     # url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
#     url(r'^report/wip/$',views.wip ,name='wip'),
#     url(r'^',views.home ,name='home'),

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wmp/assembly/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.conf import settings
from django.contrib.contenttypes.fields import GenericRelation
from django.core.validators import RegexValidator

# Create your models here.
from product.models import Product
from routing.models import RoutingDetail

ACTIVE='A'
DEACTIVE='D'
STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DEACTIVE, 'Deactive'),
    )

class Assembly(models.Model):
	name 			= models.CharField(max_length=50,primary_key=True,
						validators=[
										RegexValidator(
											regex='^[\w-]+$',
											message='Name does not allow special charecters',
										),
						])
	title 			= models.CharField(max_length=100,blank=True, null=True)
	product 		= models.ForeignKey(Product,
							on_delete=models.CASCADE,
							related_name='assemblys')
	slug 			= models.SlugField(unique=True,blank=True, null=True)
	description 	= models.TextField(blank=True, null=True)
	category1 		= models.CharField(max_length=50,blank=True, null=True)
	category2 		= models.CharField(max_length=50,blank=True, null=True)
	status 			= models.CharField(max_length=1,choices=STATUS_CHOICES,default=ACTIVE)
	created_date 	= models.DateTimeField(auto_now_add=True)
	modified_date 	= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 			= models.ForeignKey(settings.AUTH_USER_MODEL,
							on_delete=models.SET_NULL,
							blank=True,null=True)
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('assembly:detail', kwargs={'slug': self.slug})

	@property
	def items_count(self):
		# c = self.weight + self.runner
		return self.assembly_details.count()
	items_count.fget.short_description = "Total Items"
	# def item_count(self):
	# 	return self.bom_detail_set.count()

def create_assembly_slug(instance, new_slug=None):
    # import datetime
    default_slug = '%s' % (instance.name)
    slug = slugify(default_slug)
    if new_slug is not None:
        slug = new_slug
    qs = Assembly.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.count())
        return create_assembly_slug(instance, new_slug=new_slug)
    return slug

def pre_save_assembly_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_assembly_slug(instance)

pre_save.connect(pre_save_assembly_receiver, sender=Assembly)



from bom.models import Bom_Detail

class Assembly_Detail(models.Model):
	ordered 			= models.IntegerField(default=1)
	assembly 			= models.ForeignKey(Assembly,
								on_delete=models.CASCADE,
								related_name='assembly_details')
	part 				= models.ForeignKey(Bom_Detail,
								on_delete=models.CASCADE,
								related_name='assembly_details')
	title 				= models.CharField(max_length=100,blank=True, null=True)
	datecode_regexp 	= models.CharField(max_length=50,blank=True, null=True,
								verbose_name='Datecode RegExp Validation')
	lotcode_regexp 		= models.CharField(max_length=50,blank=True, null=True,
								verbose_name='Lotcode RegExp Validation')
	supplycode_regexp 	= models.CharField(max_length=50,blank=True, null=True,
								verbose_name='Supplycode RegExp Validation')
	sn_regexp 			= models.CharField(max_length=50,blank=True, null=True,
								verbose_name='Serial number RegExp Validation')
	slug 				= models.SlugField(unique=True,blank=True, null=True)
	description 		= models.TextField(max_length=255,blank=True, null=True)
	category1 			= models.CharField(max_length=50,blank=True, null=True)
	category2 			= models.CharField(max_length=50,blank=True, null=True)
	critical 			= models.BooleanField(default=False)
	msd_control			= models.BooleanField(default=False,verbose_name='Enable MSD Control')
	status 				= models.CharField(max_length=1,choices=STATUS_CHOICES,default=ACTIVE)
	created_date 		= models.DateTimeField(auto_now_add=True)
	modified_date 		= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 				= models.ForeignKey(settings.AUTH_USER_MODEL,
							on_delete=models.SET_NULL,
							blank=True,null=True)
	
	class Meta:
		unique_together = ('assembly','part')
		ordering 		= ['ordered',]

	def __str__(self):
		return ('%s' % (self.part))

	def get_absolute_url(self):
		return reverse('assembly:assembly-detail', kwargs={'slug': self.slug})

def create_assembly_detail_slug(instance, new_slug=None):
    # import datetime
    default_slug = '%s-%s' % (instance.assembly,instance.part)
    slug = slugify(default_slug)
    if new_slug is not None:
        slug = new_slug
    qs = Assembly_Detail.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.count())
        return pre_save_assembly_detail_receiver(instance, new_slug=new_slug)
    return slug

def pre_save_assembly_detail_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_assembly_detail_slug(instance)

pre_save.connect(pre_save_assembly_detail_receiver, sender=Assembly_Detail)



class Assembly_Usage(models.Model):
	routingdetail 			= models.ForeignKey(RoutingDetail, 
								on_delete=models.CASCADE,
								related_name ='assembly_usages')
	assembly 				= models.ForeignKey(Assembly, 
								on_delete=models.CASCADE,
								related_name ='assembly_usages')
	ordered 				= models.IntegerField(default=1)
	slug 					= models.SlugField(unique=True,blank=True, null=True)
	title 					= models.CharField(max_length=100,blank=True, null=True)
	description 			= models.TextField(max_length=255,blank=True, null=True)
	category1 				= models.CharField(max_length=50,blank=True, null=True)
	category2 				= models.CharField(max_length=50,blank=True, null=True)
	status 					= models.CharField(max_length=1,choices=STATUS_CHOICES,default=ACTIVE)
	created_date 			= models.DateTimeField(auto_now_add=True)
	modified_date 			= models.DateTimeField(blank=True, null=True,auto_now=True)
	user 					= models.ForeignKey(settings.AUTH_USER_MODEL,
								on_delete=models.SET_NULL,
								blank=True,null=True)

	def __str__(self):
		return ('%s on %s' % (self.assembly,self.routingdetail))

	def get_absolute_url(self):
		return reverse('assembly_usage:detail', kwargs={'slug': self.slug})

def create_assembly_usage_slug(instance, new_slug=None):
    # import datetime
    default_slug = '%s-%s' % (instance.assembly,instance.routingdetail)
    slug = slugify(default_slug)
    if new_slug is not None:
        slug = new_slug
    qs = Assembly_Usage.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.count())
        return pre_save_assembly_usage_receiver(instance, new_slug=new_slug)
    return slug

def pre_save_assembly_usage_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_assembly_usage_slug(instance)

pre_save.connect(pre_save_assembly_usage_receiver, sender=Assembly_Usage)

wmp/assembly/views.py
from django.shortcuts import render
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView
from django.db.models import Q,F

from .models import Assembly,Assembly_Detail

class AssemblyListView(ListView):
	model = Assembly
	paginate_by = 100
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query :
			return Assembly.objects.filter(Q(name__icontains=query) |
									Q(title__icontains=query) |
									Q(product__name__icontains=query) |
									Q(description__icontains=query) ).order_by('-modified_date')
		return Assembly.objects.all().order_by('-modified_date')

class AssemblyDetailView(DetailView):
	model = Assembly


class AssemblyDetailDetailView(DetailView):
	model = Assembly_Detail

wmp/templates/assembly/assembly_detail.html
{% extends "base.html" %}


{% block title %}
	Assembly : {{ object.name }}
{% endblock %}

{% block content %}
	<div class="wrapper">	
		<h1>Name : {{object.name}}</h1> 
		<a href="../">Back to Assembly list</a><br>
		<i>Created date : {{object.created_date}} -- {{object.created_user}}</i><br>
		<i>Modified date : {{object.modified_date}}</i>

		<div class="row">
			          <div class="col-md-6">
			            <h4>Basic Information</h4>
					<table class="table">
					  <tbody>
					  	<tr>
					  		<td>Title</td>
					      	<td>{{object.title}}</td>
					    </tr>
					  	<tr>
					  		<td>Description</td>
					      	<td>{{object.description|linebreaks}}</td>
					    </tr>

					    <tr>
					  		<td>Product</td>
					      	<td><a href="{{object.product.get_absolute_url}}">{{object.product}}</a></td>
					    </tr>


					    <tr>
					  		<td>Category</td>
					      	<td>{{object.category1}}/{{object.category2}}</td>
					    </tr>

					    <tr>
					  		<td>Status</td>
					      	<td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
					    </tr>
					  </tbody>
					</table>
				</div>

				<div class="col-md-6">
			            <h4>Assembly Usage</h4>
			            {% for usage in object.assembly_usages.all|dictsort:"modified_date" %}
			            	<li><a href="{{usage.routingdetail.get_absolute_url}}">{{usage.routingdetail}}</a></li>
			            {% endfor %}
			    </div>

		</div>

		<div class="row">
			<div class="col-md-12">
				<h4>Assembly Items</h4>
				<table class="table table-bordered">
			      <thead>
			        <tr>
			          <th scope="col">Order</th>
			          <th scope="col">Part</th>
			          <th scope="col">Type</th>
			          <th scope="col">Critical</th>
			          <th scope="col">MSD Control</th>
			          <th scope="col">Title</th>
			         <th scope="col">Modify Date</th>
			         <th scope="col">Status</th>
			        </tr>
			      </thead>
      				<tbody>

				
				{% for item in object.assembly_details.all|dictsort:"ordered" %}
			           <tr>
			           		<td><a href="{{item.get_absolute_url}}">{{item.ordered}}</a></td>
			           		<td>{{item.part}}</td>
			           		<td>{{item.part.pn_type}}</td>
			           		<td><i class="fa {% if item.critial %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if item.critial %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>

			           		<td><i class="fa {% if item.msd_control %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if item.msd_control %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>

			           		<td>{{item.title}}</td>
			           		<td>{{item.modified_date}}</td>
			           		<td><i class="fa {% if item.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if item.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
			           </tr>
			     {% endfor %}
			 		</tbody>
			 	</table>
			</div>
		</div>

	</div>
{% endblock content %}

wmp/templates/assembly/assembly_detail_detail.html
{% extends "base.html" %}


{% block title %}
	Assembly : {{ object.name }}
{% endblock %}

{% block content %}
	<div class="wrapper">	
		<h1>Name : {{object}}</h1> 
		<a href="{{object.assembly.get_absolute_url}}">Back to Assembly list</a><br>
		<i>Created date : {{object.created_date}} -- {{object.created_user}}</i><br>
		<i>Modified date : {{object.modified_date}}</i>

		<div class="row">
			          <div class="col-md-6">
			            <h4>Basic Information</h4>
					<table class="table">
					  <tbody>
					  	<tr>
					  		<td>Order</td>
					      	<td>{{object.ordered}}</td>
					    </tr>
					  	<tr>
					  		<td>Title</td>
					      	<td>{{object.title}}</td>
					    </tr>
					    <tr>
					  		<td>Part (BOM)</td>
					      	<td><a href="{{object.part.get_absolute_url}}">{{object.part}}</a></td>
					    </tr>

					    <tr>
					  		<td>Critical</td>
					      	<td><i class="fa {% if object.critical %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.critical %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
					    </tr>

					    <tr>
					  		<td>Description</td>
					      	<td>{{object.description}}</td>
					    </tr>


					    <tr>
					  		<td>Category</td>
					      	<td>{{object.category1}}/{{object.category2}}</td>
					    </tr>

					    <tr>
					  		<td>Status</td>
					      	<td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
					    </tr>
					  </tbody>
					</table>
				</div>

				<div class="col-md-6">
			            <h4>Assembly Component Control</h4>
			            <table class="table">
						  <tbody>
						  	<tr>
						  		<td>Datecode data format</td>
						      	<td>{{object.datecode_regexp|default_if_none:''}}</td>
						    </tr>
						  	<tr>
						  		<td>Lotcode data format</td>
						      	<td>{{object.lotcode_regexp|default_if_none:''}}</td>
						    </tr>
						    <tr>
						  		<td>Supplycode data format</td>
						      	<td>{{object.supplycode_regexp|default_if_none:''}}</td>
						    </tr>

						    <tr>
						  		<td>MSD Control</td>
						      	<td><i class="fa {% if object.msd_control %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.msd_control %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
						    </tr>

						  </tbody>
						</table>
						<h4>Assembly Module Control</h4>
						<table class="table">
						<tbody>
						  	<tr>
						  		<td>Module Serial number format</td>
						      	<td>{{object.sn_regexp|default_if_none:''}}</td>
						    </tr>
						  	
						  </tbody>
						</table>
			   </div>

		</div>

		
		</div>

	</div>
{% endblock content %}

wmp/templates/assembly/assembly_list.html
{% extends 'base.html' %}

{% block title %}8AM - Assembly list{% endblock %}

{% block content %}

	<h1>Assembly List</h1>
  <a href="../"><i class="fa fa-home" style="font-size:24px;color:blue" aria-hidden="true"></i></a>
	<div class="wrapper">	


    <form class='form' method='GET' action='.'>
                        <input type='text' id='search' placeholder="Search assembly" name="q" value='{{ request.GET.q}}'>
                        <button class='btn btn-default' type='submit'>Search</button>
                        <a href="{% url 'assembly:list'  %}">Clear result</a>
    </form>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Assembly name</th>
          <th scope="col">Title</th>
          <th scope="col">Product</th>
          <th scope="col">Item count</th>
         <th scope="col">Created Date</th>
         <th scope="col">Modify Date</th>
         <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
		
    		{% for object in object_list %}
          <tr>
            <td><a href="{{object.get_absolute_url}}">{{object}}</a> </td>
            <td>{{object.title}} </td>
            <td>{{object.product}} </td>
            <td>{{object.items_count}} </td>
            <td>{{object.created_date}}</td>
            <td>{{object.modified_date}}</td>
            <td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
          </tr>
    		{% endfor %}
      </tbody>
    </table>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

	</div>
		
{% endblock content %}


{% block stylesheet %}
{% endblock stylesheet %}