wmp/bom/api/urls.py
# from django.conf.urls import url
# from django.contrib import admin

# from .views import (
#     BomListAPIView,
#     BomDetailAPIView,
#     BomCreateAPIView,
#     BomDeleteAPIView,
#     BomUpdateAPIView
#     )

# urlpatterns = [
# 	url(r'^$', BomListAPIView.as_view(), name='list'),
# 	url(r'^create/$',BomCreateAPIView.as_view(),name='create'),
# 	url(r'^(?P<slug>[\w-]+)/$',BomDetailAPIView.as_view(), name='detail'),
# 	url(r'^(?P<slug>[\w-]+)/delete/$', BomDeleteAPIView.as_view(),name='delete'),
# 	url(r'^(?P<slug>[\w-]+)/update/$', BomUpdateAPIView.as_view(),name='update'),
 
# ]

wmp/bom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (BomDetailView,
					BomListView,
					BomDetailListView,
					BomDetailDetailView)


urlpatterns = [
	# Page
	url(r'^$',BomListView.as_view(),name='list'),
	url(r'^item/$',BomDetailListView.as_view(),name='item-list'),
	url(r'^item/(?P<slug>[-\w]+)/$',BomDetailDetailView.as_view(),name='item-detail'),
    url(r'^(?P<slug>[-\w]+)/$',BomDetailView.as_view(),name='detail'),

]

wmp/wmp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .routers import router

from . import views

from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    url(r'^$',views.home ,name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^graphql/', GraphQLView.as_view(
        graphiql =True,
        schema=schema
    )),
    # Token
    url(r'^api/', include(router.urls)),
    url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),

    
    url(r'^assembly/',include(('assembly.urls','assembly'),namespace='assembly')),
    url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
    url(r'^component/',include(('component.urls','component'),namespace='component')),
    url(r'^cache/',include(('cache.urls','cache'),namespace='cache')),
    url(r'^item/',include(('item.urls','item'),namespace='item')),
    url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
    url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
    url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
    url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
    url(r'^product/',include(('product.urls','product'),namespace='product')),
    url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
    url(r'^routing-detail/',include(('routing.urls','routing-detail'),namespace='routing-detail')),
    url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
    url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
    url(r'^symptom/',include(('symptom.urls','symptom'),namespace='symptom')),
    url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib import admin
# admin.site.site_header = '8 O\'Clock Manufacturing Platform'
# admin.site.site_title = '8 O\'Clock Manufacturing Platform'

admin.site.site_header = '8AM Manufacturing Platform'
admin.site.site_title = '8AM Manufacturing Platform'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'wmp.views.bad_request'
# handler403 = 'wmp.views.permission_denied'
# handler404 = 'wmp.views.page_not_found'
# handler500 = 'wmp.views.server_error'

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # Page
    
#     url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
#     url(r'^bom-detail/',include(('bom_detail.urls','bom_detail'),namespace='bom_detail')),
#     url(r'^hook/',include(('hook.urls','hook'),namespace='hook')),
#     url(r'^item/',include(('item.urls','item'),namespace='item')),
#     url(r'^item-list/',include(('item_list.urls','item_list'),namespace='item-list')),
#     url(r'^failure/',include(('failure.urls','failure'),namespace='failure')),
#     url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
#     url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
#     url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
#     url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
#     url(r'^product/',include(('product.urls','product'),namespace='product')),
#     url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
#     url(r'^routing-accept/',include(('routing_accept.urls','routing_accept'),namespace='routing-accept')),
#     url(r'^routing-detail/',include(('routing_detail.urls','routing_detail'),namespace='routing-detail')),
#     url(r'^routing-next/',include(('routing_next.urls','routing_next'),namespace='routing-next')),
#     url(r'^routing-reject/',include(('routing_reject.urls','routing_reject'),namespace='routing-reject')),
#     url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
#     url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
#     url(r'^symptom-code/',include(('symptom_code.urls','symptom_code'),namespace='symptom-code')),
#     url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    
#     # API
#     url(r'api/bom/', include(('bom.api.urls','bom'), namespace='bom-api')),
#     url(r'api/bom-detail/', include(("bom_detail.api.urls",'bom_detail'), namespace='bom_detail-api')),
#     url(r'api/defectcode/', include(("defect_code.api.urls",'defectcode'), namespace='defectcode-api')),
#     url(r'api/item/', include(("item.api.urls",'item'), namespace='item-api')),
#     url(r'api/item-list/', include(("item_list.api.urls",'item_list'), namespace='item_list-api')),
#     url(r'api/failure/', include(("failure.api.urls",'failure'), namespace='failure-api')),
#     url(r'api/hook/', include(("hook.api.urls",'hook'), namespace='hook-api')),
#     url(r'api/routing/', include(("routing.api.urls",'routing'), namespace='routing-api')),
#     url(r'api/routing-accept/', include(("routing_accept.api.urls",'routing_accept'), namespace='routing_accept-api')),
#     url(r'api/routing-next/', include(("routing_next.api.urls",'routing_next'), namespace='routing_next-api')),
#     url(r'api/routing-reject/', include(("routing_reject.api.urls",'routing_reject'), namespace='routing_reject-api')),
#     url(r'api/performing/', include(("performing.api.urls",'performing'), namespace='performing-api')),
#     url(r'api/serialnumber/', include(("serialnumber.api.urls",'serialnumber'), namespace='serialnumber-api')),
#     url(r'api/workorder/', include(("workorder.api.urls",'workorder'), namespace='workorder-api')),
#     url(r'api/product/', include(("product.api.urls",'product'), namespace='product-api')),
#     url(r'api/operation/', include(("operation.api.urls",'operation'), namespace='operation-api')), 
#     url(r'api/routing-detail/', include(("routing_detail.api.urls",'routing_detail'), namespace='routing_detail-api')),
#     url(r'api/parameter/', include(("parameter.api.urls",'parameter'), namespace='parameter-api')),
#     url(r'api/parametric/', include(("parametric.api.urls",'parametric'), namespace='parametric-api')),
#     url(r'api/snippet/', include(("snippet.api.urls",'snippet'), namespace='snippet-api')),
#     url(r'api/symptomcode/', include(("symptom_code.api.urls",'snippet'), namespace='symptomcode-api')),
#     url(r'api/user-profile/', include(("user_profile.api.urls",'user_profile'), namespace='userprofile-api')),

#     #Restful Authentication
#     url(r'^api-auth/', include('rest_framework.urls')),
#     # Token
#     url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
#     url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
#     url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
#     # url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
#     url(r'^report/wip/$',views.wip ,name='wip'),
#     url(r'^',views.home ,name='home'),

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wmp/bom/api/views.py
# from django.db.models import Q

# from rest_framework.generics import (
# 	CreateAPIView,
# 	DestroyAPIView,
# 	ListAPIView,
# 	UpdateAPIView,
# 	RetrieveAPIView,
# 	RetrieveUpdateAPIView,
# 	RetrieveUpdateDestroyAPIView
# 	)

# from rest_framework.filters import (
# 	SearchFilter,
# 	OrderingFilter,
# 	)

# from rest_framework.permissions import (
# 	AllowAny,
# 	IsAuthenticated,
# 	IsAdminUser,
# 	IsAuthenticatedOrReadOnly,
# 	)


# from bom.models import Bom

# from .serialize import (BomListSerializer,
# 						BomCreateSerializer,
# 						BomDetailSerializer,
# 						BomUpdateSerializer)



# class BomListAPIView(ListAPIView):
# 	queryset = None #Booking.objects.all()
# 	serializer_class = BomListSerializer
# 	filter_backends = [SearchFilter,OrderingFilter]
# 	search_fields = ['q']
# 	def get_queryset(self,*args,**kwargs):
# 		queryset_list = Bom.objects.all()
# 		name = self.request.GET.get("q")
# 		if name != None :
# 			queryset_list = Bom.objects.filter(
# 					Q(name__icontains = name))
# 		return queryset_list
# 	# pagination_class = PostPageNumberPagination

# class BomDetailAPIView(RetrieveAPIView):
# 	queryset= Bom.objects.all()
# 	serializer_class = BomDetailSerializer
# 	lookup_field = 'slug'
# 	# print ("vessel details")

# class BomDeleteAPIView(DestroyAPIView):
# 	queryset= Bom.objects.all()
# 	serializer_class= BomDetailSerializer
# 	lookup_field='slug'
# 	# permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]


# class BomCreateAPIView(CreateAPIView):
# 	queryset= Bom.objects.all()
# 	serializer_class= BomCreateSerializer
# 	# permission_classes = [IsAuthenticated]

# # 	def perform_create(self,serializer):
# # 		print ('Voy is %s' % self.kwargs.get('voy'))
# # 		serializer.save()
# class BomUpdateAPIView(RetrieveUpdateDestroyAPIView):
# 	queryset=Bom.objects.all()
# 	serializer_class=BomUpdateSerializer
# 	lookup_field='slug'

wmp/bom/views.py
from django.shortcuts import render
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView
from django.db.models import Q,F

from .models import Bom,Bom_Detail

class BomListView(ListView):
	model = Bom
	paginate_by = 100
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query :
			return Bom.objects.filter(Q(name__icontains=query) |
									Q(title__icontains=query) |
									Q(pn__name__icontains=query) |
									Q(fg_pn__name__icontains=query) |
									Q(description__icontains=query) ).order_by('-modified_date')
		return Bom.objects.all().order_by('-modified_date')

class BomDetailView(DetailView):
	model = Bom



class BomDetailListView(ListView):
	model = Bom_Detail
	paginate_by = 100
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query :
			return Bom_Detail.objects.filter(Q(rd__icontains=query) |
									Q(title__icontains=query) |
									Q(pn__icontains=query) |
									Q(customer_pn__icontains=query) |
									Q(description__icontains=query) ).order_by('-modified_date')
		return Bom_Detail.objects.all().order_by('-modified_date')

class BomDetailDetailView(DetailView):
	model = Bom_Detail

wmp/templates/bom/bom_detail.html
{% extends "base.html" %}


{% block title %}
	Assembly : {{ object.name }}
{% endblock %}

{% block content %}
	<div class="wrapper">	
		<h1>Name : {{object.name}}</h1> 
		<a href="../">Back to BOM list</a><br>
		<i>Created date : {{object.created_date}} -- {{object.created_user}}</i><br>
		<i>Modified date : {{object.modified_date}}</i>

		<div class="row">
			          <div class="col-md-6">
			            <h4>Basic Information</h4>
					<table class="table">
					  <tbody>
					  	<tr>
					  		<td>Part number</td>
					      	<td>{{object.pn}}</td>
					    </tr>
					    <tr>
					  		<td>Part Rev</td>
					      	<td>{{object.rev}}</td>
					    </tr>
					    <tr>
					  		<td>FG Part number</td>
					      	<td>{{object.fg_pn}}</td>
					    </tr>
					    <tr>
					  		<td>FG Part Rev</td>
					      	<td>{{object.fg_rev}}</td>
					    </tr>
					  	<tr>
					  		<td>Title</td>
					      	<td>{{object.title}}</td>
					    </tr>
					  	<tr>
					  		<td>Description</td>
					      	<td>{{object.description|linebreaks}}</td>
					    </tr>

					    


					    <tr>
					  		<td>Category</td>
					      	<td>{{object.category1}}/{{object.category2}}</td>
					    </tr>

					    <tr>
					  		<td>Status</td>
					      	<td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
					    </tr>
					  </tbody>
					</table>
				</div>

				

		</div>

		<div class="row">
			<div class="col-md-12">
				<h4>BOM Items</h4>
				<table class="table table-bordered">
			      <thead>
			        <tr>
			          <th scope="col">Ref Des.</th>
			          <th scope="col">Part number</th>
			          <th scope="col">Title</th>
			          <th scope="col">Customer PN</th>
			          <th scope="col">Type</th>
			          <th scope="col">Critial</th>
			         <th scope="col">Modify Date</th>
			         <th scope="col">Status</th>
			        </tr>
			      </thead>
      				<tbody>

				
				{% for item in object.items.all|dictsort:"rd" %}
			           <tr>
			           		<td><a href="{{item.get_absolute_url}}">{{item.rd}}</a></td>
			           		<td>{{item.pn}}</td>
			           		<td>{{item.title}}</td>
			           		<td>{{item.customer_pn}}</td>
			           		<td>{{item.pn_type}}</td>
			           		<td><i class="fa {% if item.critial %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if item.critial %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
			           		<td>{{item.modified_date}}</td>
			           		<td><i class="fa {% if item.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if item.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
			           </tr>
			     {% endfor %}
			 		</tbody>
			 	</table>
			</div>
		</div>

		

	</div>
{% endblock content %}

wmp/templates/bom/bom_detail_detail.html
{% extends "base.html" %}


{% block title %}
  Assembly : {{ object.name }}
{% endblock %}

{% block content %}
  <div class="wrapper"> 
    <h1>Name : {{object}}</h1> 
    <a href="../">Back to BOM item list</a><br>
    <i>Created date : {{object.created_date}} -- {{object.created_user}}</i><br>
    <i>Modified date : {{object.modified_date}}</i>

    <div class="row">
      <div class="col-md-6">
        <h4>Basic Information</h4>
          <table class="table">
            <tbody>
              <tr>
                <td>Ref Des</td>
                  <td>{{object.rd}}</td>
              </tr>
              <tr>
                <td>Part number</td>
                  <td>{{object.pn}}</td>
              </tr>
              <tr>
                <td>Customer Part number</td>
                  <td>{{object.customer_pn}}</td>
              </tr>
              <tr>
                <td>Part Type</td>
                  <td>{{object.pn_type}}</td>
              </tr>

              <tr>
                <td>Critial</td>
                  <td><i class="fa {% if object.critial %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.critial %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
              </tr>

              <tr>
                <td>BOM</td>
                  <td><a href="{{object.bom.get_absolute_url}}">{{object.bom}}</a></td>
              </tr>

              <tr>
                <td>Title</td>
                  <td>{{object.title}}</td>
              </tr>
              <tr>
                <td>Description</td>
                  <td>{{object.description|linebreaks}}</td>
              </tr>

              


              <tr>
                <td>Category</td>
                  <td>{{object.category1}}/{{object.category2}}</td>
              </tr>

              <tr>
                <td>Status</td>
                  <td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
              </tr>
            </tbody>
          </table>
        </div>


        <div class="col-md-6">
        <h4>Packaging Information</h4>
          <table class="table">
            <tbody>
              <tr>
                <td>Pin</td>
                  <td>{{object.pin}}</td>
              </tr>
              <tr>
                <td>Thickness</td>
                  <td>{{object.thickness}}</td>
              </tr>

              <tr>
                <td>Package Family</td>
                  <td>{{object.package_family}}</td>
              </tr>
              <tr>
                <td>Package Type</td>
                  <td>{{object.package}}</td>
              </tr>

            </tbody>
          </table>
        </div>

        

    </div>

    

  </div>
{% endblock content %}

wmp/templates/bom/bom_detail_list.html
{% extends 'base.html' %}

{% block title %}8AM - BOM Item list{% endblock %}

{% block content %}

	<h1>BOM Item List</h1>
  <a href="../"><i class="fa fa-home" style="font-size:24px;color:blue" aria-hidden="true"></i></a>
	<div class="wrapper">	


    <form class='form' method='GET' action='.'>
                        <input type='text' id='search' placeholder="Search bom item" name="q" value='{{ request.GET.q}}'>
                        <button class='btn btn-default' type='submit'>Search</button>
                        <a href="{% url 'bom:item-list'  %}">Clear result</a>
    </form>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Ref Des</th>
          <th scope="col">Part number</th>
          <th scope="col">Customer Part</th>
          <th scope="col">Part Type</th>

          <th scope="col">Title</th>
         <th scope="col">Created Date</th>
         <th scope="col">Modify Date</th>
         <th scope="col">Status</th>
        </tr>
      </thead>
      <tbody>
		
    		{% for object in object_list %}
          <tr>
            <td><a href="{{object.get_absolute_url}}">{{object.rd}}</a></td>
            <td>{{object.pn}} </td>
         
            <td>{{object.customer_pn}} </td>
            <td>{{object.pn_type}} </td>
            <td>{{object.title}} </td>
            
            <td>{{object.created_date}}</td>
            <td>{{object.modified_date}}</td>
            <td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
          </tr>
    		{% endfor %}
      </tbody>
    </table>

    {{ page_obj.start_index }} to {{ page_obj.end_index }} of {{ page_obj.paginator.count }} record(s). <br>
     {% if is_paginated %}
                  <ul class="pagination">
                    {% if page_obj.has_previous %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}
                    {% for i in paginator.page_range %}
                      {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                      {% else %}
                        <li><a href="?q={{ request.GET.q}}&page={{ i }}">{{ i }}</a></li>
                      {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                      <li><a href="?q={{ request.GET.q}}&page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                      <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}
                  </ul>
      {% endif %}

	</div>
		
{% endblock content %}


{% block stylesheet %}
{% endblock stylesheet %}

wmp/templates/bom/bom_list.html
<ul>
{% for object in object_list %}
	<li><a href="{{ object.get_absolute_url }}">{{object.name}}</a></li>
{% endfor %}
</ul>