wmp/bom/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (BomDetailView,
					BomListView,
					BomDetailListView,
					BomDetailDetailView)


urlpatterns = [
	# Page
	url(r'^$',BomListView.as_view(),name='list'),
	url(r'^item/$',BomDetailListView.as_view(),name='item-list'),
	url(r'^item/(?P<slug>[-\w]+)/$',BomDetailDetailView.as_view(),name='item-detail'),
    url(r'^(?P<slug>[-\w]+)/$',BomDetailView.as_view(),name='detail'),

]

wmp/wmp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from .routers import router

from . import views

from graphene_django.views import GraphQLView
from .schema import schema

urlpatterns = [
    url(r'^$',views.home ,name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^graphql/', GraphQLView.as_view(
        graphiql =True,
        schema=schema
    )),
    # Token
    url(r'^api/', include(router.urls)),
    url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
    url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),

    
    url(r'^assembly/',include(('assembly.urls','assembly'),namespace='assembly')),
    url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
    url(r'^component/',include(('component.urls','component'),namespace='component')),
    url(r'^cache/',include(('cache.urls','cache'),namespace='cache')),
    url(r'^item/',include(('item.urls','item'),namespace='item')),
    url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
    url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
    url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
    url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
    url(r'^product/',include(('product.urls','product'),namespace='product')),
    url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
    url(r'^routing-detail/',include(('routing.urls','routing-detail'),namespace='routing-detail')),
    url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
    url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
    url(r'^symptom/',include(('symptom.urls','symptom'),namespace='symptom')),
    url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

from django.contrib import admin
# admin.site.site_header = '8 O\'Clock Manufacturing Platform'
# admin.site.site_title = '8 O\'Clock Manufacturing Platform'

admin.site.site_header = '8AM Manufacturing Platform'
admin.site.site_title = '8AM Manufacturing Platform'

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'wmp.views.bad_request'
# handler403 = 'wmp.views.permission_denied'
# handler404 = 'wmp.views.page_not_found'
# handler500 = 'wmp.views.server_error'

# urlpatterns = [
#     url(r'^admin/', admin.site.urls),
#     # Page
    
#     url(r'^bom/',include(('bom.urls','bom'),namespace='bom')),
#     url(r'^bom-detail/',include(('bom_detail.urls','bom_detail'),namespace='bom_detail')),
#     url(r'^hook/',include(('hook.urls','hook'),namespace='hook')),
#     url(r'^item/',include(('item.urls','item'),namespace='item')),
#     url(r'^item-list/',include(('item_list.urls','item_list'),namespace='item-list')),
#     url(r'^failure/',include(('failure.urls','failure'),namespace='failure')),
#     url(r'^operation/',include(('operation.urls','operation'),namespace='operation')),
#     url(r'^parameter/',include(('parameter.urls','parameter'),namespace='parameter')),
#     url(r'^parametric/',include(('parametric.urls','parametric'),namespace='parametric')),
#     url(r'^performing/',include(('performing.urls','performing'),namespace='performing')),
#     url(r'^product/',include(('product.urls','product'),namespace='product')),
#     url(r'^routing/',include(('routing.urls','routing'),namespace='routing')),
#     url(r'^routing-accept/',include(('routing_accept.urls','routing_accept'),namespace='routing-accept')),
#     url(r'^routing-detail/',include(('routing_detail.urls','routing_detail'),namespace='routing-detail')),
#     url(r'^routing-next/',include(('routing_next.urls','routing_next'),namespace='routing-next')),
#     url(r'^routing-reject/',include(('routing_reject.urls','routing_reject'),namespace='routing-reject')),
#     url(r'^serialnumber/',include(('serialnumber.urls','serialnumber'),namespace='serialnumber')),
#     url(r'^snippet/',include(('snippet.urls','snippet'),namespace='snippet')),
#     url(r'^symptom-code/',include(('symptom_code.urls','symptom_code'),namespace='symptom-code')),
#     url(r'^workorder/',include(('workorder.urls','workorder'),namespace='workorder')),
    
#     # API
#     url(r'api/bom/', include(('bom.api.urls','bom'), namespace='bom-api')),
#     url(r'api/bom-detail/', include(("bom_detail.api.urls",'bom_detail'), namespace='bom_detail-api')),
#     url(r'api/defectcode/', include(("defect_code.api.urls",'defectcode'), namespace='defectcode-api')),
#     url(r'api/item/', include(("item.api.urls",'item'), namespace='item-api')),
#     url(r'api/item-list/', include(("item_list.api.urls",'item_list'), namespace='item_list-api')),
#     url(r'api/failure/', include(("failure.api.urls",'failure'), namespace='failure-api')),
#     url(r'api/hook/', include(("hook.api.urls",'hook'), namespace='hook-api')),
#     url(r'api/routing/', include(("routing.api.urls",'routing'), namespace='routing-api')),
#     url(r'api/routing-accept/', include(("routing_accept.api.urls",'routing_accept'), namespace='routing_accept-api')),
#     url(r'api/routing-next/', include(("routing_next.api.urls",'routing_next'), namespace='routing_next-api')),
#     url(r'api/routing-reject/', include(("routing_reject.api.urls",'routing_reject'), namespace='routing_reject-api')),
#     url(r'api/performing/', include(("performing.api.urls",'performing'), namespace='performing-api')),
#     url(r'api/serialnumber/', include(("serialnumber.api.urls",'serialnumber'), namespace='serialnumber-api')),
#     url(r'api/workorder/', include(("workorder.api.urls",'workorder'), namespace='workorder-api')),
#     url(r'api/product/', include(("product.api.urls",'product'), namespace='product-api')),
#     url(r'api/operation/', include(("operation.api.urls",'operation'), namespace='operation-api')), 
#     url(r'api/routing-detail/', include(("routing_detail.api.urls",'routing_detail'), namespace='routing_detail-api')),
#     url(r'api/parameter/', include(("parameter.api.urls",'parameter'), namespace='parameter-api')),
#     url(r'api/parametric/', include(("parametric.api.urls",'parametric'), namespace='parametric-api')),
#     url(r'api/snippet/', include(("snippet.api.urls",'snippet'), namespace='snippet-api')),
#     url(r'api/symptomcode/', include(("symptom_code.api.urls",'snippet'), namespace='symptomcode-api')),
#     url(r'api/user-profile/', include(("user_profile.api.urls",'user_profile'), namespace='userprofile-api')),

#     #Restful Authentication
#     url(r'^api-auth/', include('rest_framework.urls')),
#     # Token
#     url(r'^api/login/', include(('user_profile.urls','user'),namespace='login')),
#     url(r'^api/token/$', TokenObtainPairView.as_view(), name='token_obtain_pair'),
#     url(r'^api/token/refresh/$', TokenRefreshView.as_view(), name='token_refresh'),
#     # url(r'^api/token/verify/$', TokenVerifyView.as_view(), name='token_verify'),
#     url(r'^report/wip/$',views.wip ,name='wip'),
#     url(r'^',views.home ,name='home'),

# ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wmp/workorder/api/urls.py
# from django.conf.urls import url
# from django.contrib import admin

# from .views import (
#     WorkOrderListAPIView,
#     WorkOrderDetailAPIView,
#     WorkOrderCreateAPIView,
#     WorkOrderDeleteAPIView,
#     WorkOrderUpdateAPIView
#     )

# urlpatterns = [
# 	url(r'^$', WorkOrderListAPIView.as_view(), name='list'),
# 	url(r'^create/$', WorkOrderCreateAPIView.as_view(),name='create'),
# 	url(r'^(?P<slug>[\w-]+)/$', WorkOrderDetailAPIView.as_view(), name='detail'),
# 	url(r'^(?P<slug>[\w-]+)/delete/$', WorkOrderDeleteAPIView.as_view(),name='delete'),
# 	url(r'^(?P<slug>[\w-]+)/update/$', WorkOrderUpdateAPIView.as_view(),name='update'),
 
# ]

wmp/workorder/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf.urls.static import static
from django.conf import settings

from .views import (WorkOrderDetailView,
					WorkOrderListView,
					onwip)



urlpatterns = [
	# Page
	url(r'^$',WorkOrderListView.as_view(),name='list'),
    url(r'^(?P<slug>[-\w]+)/$',WorkOrderDetailView.as_view(),name='detail'),
    url(r'^(?P<slug>[-\w]+)/wip/$',onwip,name='wip'),
]

wmp/workorder/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from django.urls import reverse
from django.conf import settings

from product.models import Product
from routing.models import Routing
# from serialnumber.models import SerialNumber

ACTIVE='A'
DEACTIVE='D'
STATUS_CHOICES = (
        (ACTIVE, 'Active'),
        (DEACTIVE, 'Deactive'),
    )

BTO		=	'BUILD_TO_ORDER'
BTS		=	'BUILD_TO_STOCK'
BTB		=	'BUILD_TO_BUILD'
WORKORDER_BUILD_TYPE_CHOICE = (
		(BTO,'Build to Order'),
		(BTS,'Build to Stock'),
		(BTB,'Build to Build')
	)

class WorkOrder(models.Model):
	name 				= models.CharField(max_length=50,primary_key=True,
									validators=[
										RegexValidator(
											regex='^[\w-]+$',
											message='Name does not allow special charecters',
										),
									])
	title 				= models.CharField(max_length=100,blank=True, null=True)
	description 		= models.TextField(max_length=255,blank=True, null=True)
	slug 				= models.SlugField(unique=True,blank=True, null=True)
	product 			= models.ForeignKey(Product,
							on_delete=models.CASCADE,
							related_name='workorders')
	routing 			= models.ForeignKey(Routing,
							on_delete=models.SET_NULL,
							blank=True, null=True,
							related_name='workorders')
	qty 				= models.IntegerField(default=0)
	regexp 				= models.CharField(verbose_name='RegExp Validation',max_length=100,blank=True, null=True,default='*')
	category1 			= models.CharField(max_length=50,blank=True, null=True)
	category2 			= models.CharField(max_length=50,blank=True, null=True)
	status 				= models.CharField(max_length=1,choices=STATUS_CHOICES,default=ACTIVE)
	build_type			= models.CharField(max_length=20,choices=WORKORDER_BUILD_TYPE_CHOICE,default=BTO)
	created_date 		= models.DateTimeField(auto_now_add=True)
	modified_date 		= models.DateTimeField(blank=True, null=True,auto_now=True)
	finished_date 		= models.DateTimeField(blank=True, null=True)
	user 				= models.ForeignKey(settings.AUTH_USER_MODEL,
							on_delete=models.SET_NULL,
							blank=True,null=True)
	
	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('workorder:detail', kwargs={'slug': self.slug})

	@property
	def registered(self):
		# c = self.weight + self.runner
		return self.serialnumbers.count()
	registered.fget.short_description = "Registered"

	@property
	def wip(self):
		# c = self.weight + self.runner
		return self.serialnumbers.filter(wip=True).count()
	wip.fget.short_description = "On WIP"

	@property
	def wip_detail(self):
		from serialnumber.models import SerialNumber
		from django.db.models import Q
		from django.db.models import Min,Max,Avg,StdDev,Count,Sum,Value, When,Case,IntegerField,CharField
		sns = SerialNumber.objects.filter(workorder=self.name)
		wips = sns.values('current_operation').annotate(
				total=Count('number'),last_date=Max('last_modified_date')).order_by('current_operation')
		return wips

	@property
	def overall_yield(self):
		from performing.models import Performing
		from django.db.models import Q,F
		from django.db.models import Min,Max,Avg,StdDev,Count,Sum,Value, When,Case,IntegerField,CharField
		from datetime import date
		import datetime
		end_date 		= date.today() + datetime.timedelta(days=1)
		start_date_str	= datetime.datetime.strftime(self.created_date,"%Y-%m-%d")
		end_date_str	= datetime.datetime.strftime(end_date,"%Y-%m-%d")
		psn = Performing.objects.filter(
					sn__workorder = self.name, 
					stop_time__range=[start_date_str,end_date_str])
		y = psn.values('operation').annotate(
			total_in =Count('sn'),
			total_pass=Sum(Case(When(result=True,then=Value(1)),default=Value(0),output_field=IntegerField())),
			total_fail=Sum(Case(When(result=False,then=Value(1)),default=Value(0),output_field=IntegerField())),
			first_in=Sum(Case(When(interval=1,then=Value(1)),default=Value(0),output_field=IntegerField())),
			first_pass=Sum(Case(When(Q(interval=1)&Q(result=True),then=Value(1)),default=Value(0),output_field=IntegerField())),
			first_fail=Sum(Case(When(Q(interval=1)&Q(result=False),then=Value(1)),default=Value(0),output_field=IntegerField()))
			).order_by('operation')
		return y


def create_workorder_slug(instance, new_slug=None):
    default_slug = '%s' % (instance.name)
    slug = slugify(default_slug)
    if new_slug is not None:
        slug = new_slug
    qs = WorkOrder.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug,qs.first().id)
        return create_workorder_slug(instance, new_slug=new_slug)
    return slug

def pre_save_workorder_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_workorder_slug(instance)

pre_save.connect(pre_save_workorder_receiver, sender=WorkOrder)

wmp/workorder/api/views.py
# from django.db.models import Q

# from rest_framework.generics import (
# 	CreateAPIView,
# 	DestroyAPIView,
# 	ListAPIView,
# 	UpdateAPIView,
# 	RetrieveAPIView,
# 	RetrieveUpdateAPIView,
# 	RetrieveUpdateDestroyAPIView
# 	)

# from rest_framework.filters import (
# 	SearchFilter,
# 	OrderingFilter,
# 	)

# from rest_framework.permissions import (
# 	AllowAny,
# 	IsAuthenticated,
# 	IsAdminUser,
# 	IsAuthenticatedOrReadOnly,
# 	)

# # from .serialize import VoySerializer,VoyDetailSerializer
# # from berth.models import Voy

# from workorder.models import WorkOrder
# from .serialize import (WorkOrderListSerializer,
# 						WorkOrderCreateSerializer,
# 						WorkOrderDetailSerializer,
# 						WorkOrderUpdateSerializer)



# class WorkOrderListAPIView(ListAPIView):
# 	queryset = None #Booking.objects.all()
# 	serializer_class = WorkOrderListSerializer
# 	filter_backends = [SearchFilter,OrderingFilter]
# 	search_fields = ['q']
# 	def get_queryset(self,*args,**kwargs):
# 		queryset_list = WorkOrder.objects.all()
# 		name = self.request.GET.get('q')
# 		if name != None :
# 			queryset_list = WorkOrder.objects.filter(
# 					Q(name__icontains = name))
# 		return queryset_list
# 	# pagination_class = PostPageNumberPagination

# class WorkOrderDetailAPIView(RetrieveAPIView):
# 	queryset= WorkOrder.objects.all()
# 	serializer_class = WorkOrderDetailSerializer
# 	lookup_field = 'slug'
# 	# print ("vessel details")

# class WorkOrderDeleteAPIView(DestroyAPIView):
# 	queryset= WorkOrder.objects.all()
# 	serializer_class= WorkOrderDetailSerializer
# 	lookup_field='slug'
# 	# permission_classes = [IsAuthenticatedOrReadOnly,IsOwnerOrReadOnly]


# class WorkOrderCreateAPIView(CreateAPIView):
# 	queryset= WorkOrder.objects.all()
# 	serializer_class= WorkOrderCreateSerializer
# 	# permission_classes = [IsAuthenticated]

# # 	def perform_create(self,serializer):
# # 		print ('Voy is %s' % self.kwargs.get('voy'))
# # 		serializer.save()
# class WorkOrderUpdateAPIView(RetrieveUpdateDestroyAPIView):
# 	queryset=WorkOrder.objects.all()
# 	serializer_class=WorkOrderUpdateSerializer
# 	lookup_field='slug'

wmp/workorder/views.py
from django.shortcuts import render
from django.views.generic import DetailView,CreateView,UpdateView,DeleteView,ListView
from django.db.models import Q,F
from django.db.models import Count,Sum,Value,Min,Max, When,Case,IntegerField,CharField
from .models import WorkOrder
from serialnumber.models import SerialNumber

class WorkOrderListView(ListView):
	model = WorkOrder
	paginate_by = 100
	def get_queryset(self):
		query = self.request.GET.get('q')
		if query :
			return WorkOrder.objects.filter(Q(name__icontains=query) |
									Q(title__icontains=query) |
									Q(description__icontains=query) ).order_by('-modified_date')
		return WorkOrder.objects.all().order_by('-modified_date')

class WorkOrderDetailView(DetailView):
	model = WorkOrder


def onwip(request,slug):
	sn = SerialNumber.objects.filter(workorder__slug = slug)
	query   = sn.values('current_operation').annotate(total_wip=Count('number'))
	print (query)
	return render(request, 'workorder/workorder_wip.html', {'object_list':query})

wmp/templates/workorder/workorder_detail.html
{% extends "base.html" %}


{% block title %}
	Workorder : {{ object.name }}
{% endblock %}

{% block content %}
<div class="wrapper">	
		<h1>Workorder : {{object.name}}</h1> 
		<a href="../">Back to Workorder list</a><br>
		<i>Created date : {{object.created_date}} -- {{object.user}}</i><br>
		<i>Modified date : {{object.modified_date}}</i>

		<div class="row">
          <div class="col-md-6">
            <h4>Basic Information</h4>
		<table class="table">
		  <tbody>
		  	<tr>
		  		<td>Title</td>
		      	<td>{{object.title}}</td>
		    </tr>
		  	<tr>
		  		<td>Description</td>
		      	<td>{{object.description|linebreaks}}</td>
		    </tr>
		    <tr>
		  		<td>Slug</td>
		      	<td>{{object.slug}}</td>
		    </tr>
		    <tr>
		  		<td>Product</td>
		      	<td>
		      		<a href="{{object.product.get_absolute_url}}">
		      		{{object.product}}
		      		</a>
		      	</td>
		    </tr>
		    <tr>
		  		<td>Routing</td>
		      	<td>
		      		{% if object.routing %}
		      		<a href="{{object.routing.get_absolute_url}}">
		      		{{object.routing}}
		      		</a>
		      		{% endif %}
		      	</td>
		    </tr>
		    <tr>
		  		<td>RegExp</td>
		      	<td>{{object.regexp}}</td>
		    </tr>
		    <tr>
		  		<td>Qty</td>
		      	<td>{{object.qty}}</td>
		    </tr>
		    <tr>
		  		<td>Registered</td>
		      	<td>{{object.registered}}</td>
		    </tr>

		    <tr>
		  		<td>Category</td>
		      	<td>{{object.category1}}/{{object.category2}}</td>
		    </tr>

		    <tr>
		  		<td>Status</td>
		      	<td><i class="fa {% if object.status == 'A' %} ' fa-check-circle '  {% else %} ' fa-times-circle ' {% endif %} {% if object.status == 'A' %} true  {% else %} false {% endif %}" aria-hidden="true"></i></td>
		    </tr>
		  </tbody>
		</table>
	</div>

		<div class="col-md-6">
            <h4>Registered Serial number.</h4>
            {% for sn in object.serialnumbers.all|dictsort:"number" %}
            	<span><a href="{{sn.get_absolute_url}}">
            		{% if sn.wip %}
            			{{sn.number}}
            		{% else %}
            			<strike>{{sn.number}}</strike>
            		{% endif %}
            	</a></span> |
            {% endfor %}
        </div>

    </div><!-- end row-->

    <div class="row">
          <div class="col-md-6">
          	<h4>Current WIP</h4>
          	<table class="table table-bordered">
			      <thead>
			        <tr>
			          <th scope="col">Operation</th>
			          <th scope="col">Total Wip</th>
			          <th scope="col">Last update</th>
			        </tr>
			      </thead>
			      <tbody>

		            {% for opt in object.wip_detail %}
		            	<tr>
		            	 <td>{{opt.current_operation}}</td>
		            	 <td><a href="{% url 'serialnumber:list' %}?workorder={{object}}&operation={{opt.current_operation}}">{{opt.total}}</a></td>
		            	 <td>{{opt.last_date}}</td>
		            	</tr>
		            {% endfor %}
		        </tr>
		    	</tbody>
		    </table>
          </div>
      </div> <!-- End Row -->

      	<div class="row">
          <div class="col-md-6">
          	<h4>Overall Yield</h4>
          		<table class="table table-bordered">
					      <thead>
					        <tr>
					          <th scope="col">Operation</th>
					          <th scope="col">First-in</th>
					          <th scope="col">First-Passed</th>
					          <th scope="col">First-Failed</th>
					          <th scope="col">FPY</th>
					          <th scope="col">All-in</th>
					          <th scope="col">All-Passed</th>
					          <th scope="col">All-Failed</th>
					          <th scope="col">Accum-Yield</th>
					        </tr>
					      </thead>
					      <tbody>

				            {% for opt in object.overall_yield %}
				            	<tr>
				            	 <td>{{opt.operation}}</td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}&interval=1">
				            	 {{opt.first_in}}</a></td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}&interval=1&result=true">{{opt.first_pass}}</a></td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}&interval=1&result=false">{{opt.first_fail}}</a></td>
				            	 <td>XX%</td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}">
				            	 {{opt.total_in}}</a></td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}&result=true">{{opt.total_pass}}</a></td>
				            	 <td><a href="{% url 'performing:list' %}?workorder={{object}}&operation={{opt.operation}}&result=false">{{opt.total_fail}}</a></td>
				            	 <td>XX%</td>
				            	</tr>
				            {% endfor %}
				        </tr>
				    	</tbody>
				    </table>
          </div>
     </div><!-- end row-->

			    




	</div> <!-- end wrapper-->
{% endblock content %}

wmp/templates/workorder/workorder_wip.html
{% extends "../base.html" %}


{% block title %}
	Serialnumber Detail
{% endblock %}

{% block content %}
<main role="main" class="container">

    <div class="row">
          <div class="col-md-12">
            <h4>Wip Information</h4>
            <table class="table table-hover">
		  <thead >
		    <tr>
		      <th scope="col">Serial number</th>
		      <th scope="col">Work order</th>
		      <th scope="col">Current Operation</th>
		      <th scope="col">Previous Operation</th>
		      <th scope="col">Datetime</th>
		      <th scope="col">Aging</th>
		      <th scope="col">WIP</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for operation in object_list %}
		  		<tr>
		  			<td><a href="{{ operation.get_absolute_url }}">{{operation.number}}</a></td>
		  			<td>{{operation.workorder}}</td>
		  			<td>{{operation.current_operation}}</td>
		  			<td>{{operation.last_operation}}</td>
		  			<td>{{operation.last_modified_date}}</td>
		  			<td>{{operation.last_modified_date|timesince}}</td>
		  			<td>{{operation.wip}}</td>
		  			
		  		</tr>
		  	{% empty %}
		  		No WIP Information
		  	{% endfor %}
		  </tbody>
		</table>
        </div>

        <!-- <div class="col-md-6">
            <h4>Component Information</h4>
        </div> -->
    </div> 
</main>

{% endblock content %}